Closes #827
petrobras/ross pull request #925
Opened 2022-11-17 13:33 UTC by karenperezz

Class for probes.

2022-11-24 17:17 UTC, raphaeltimbo requested changes
Hi @karenperezz !
I have left some comments in the code.
Additionally, we should have some tests with this class.
The idea would be duplicate a test where we have the current use of a tuple to represent the probe, and replace this tuple with an object instantiated from the Probe class.

The name of the file could also be just 'probe.py' instead of probeclass.py.

2022-11-24 17:17 UTC, raphaeltimbo commented on probeclass.py
> +    def __init__(self, node, angle, tag=None):
Here we should have a docstring explaining each argument.

2022-11-24 17:17 UTC, raphaeltimbo commented on probeclass.py
> +            return [(self.node, self.angle)]
I did not understand how this method would be used in the code.
Could you please explain in more detail in the PR?

2023-01-10 10:30 UTC, ross-bott commented
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

2023-03-16 17:04 UTC, marcusfilipesr commented
@raphaeltimbo, this PR is almost finished. It is lacking the tests and a few modifications that you asked for, @karenperezz is about to implement that.

2023-04-04 11:09 UTC, marcusfilipesr approved these changes

2023-04-24 18:46 UTC, marcusfilipesr commented
@raphaeltimbo, do you think we can merge this PR, after forcing update with `master`.

2023-04-27 20:39 UTC, raphaeltimbo approved these changes

2023-04-27 20:56 UTC, merged